name: Update and Package Textweaver

on:
  push:
    branches:
      - main  # or the branch you work on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # or your desired version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -e .  # This installs your package in an editable mode

    - name: Test with pytest
      run: |
        pytest ./tests

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build and publish
      env:
        TWINE_USERNAME: __token__  # Using PyPI token
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # This uses your stored secret token
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        python setup.py sdist bdist_wheel
        twine upload dist/*